# Generated by Django 2.2.6 on 2019-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sap_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
