# Generated by Django 2.2.6 on 2019-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191008_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dept_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
